os2display_poster_events:
    path:     /api/os2display_poster/events
    defaults: { _controller: Os2DisplayPosterBundle:Poster:events }

os2display_poster_event:
    path:     /api/os2display_poster/events/{id}
    defaults: { _controller: Os2DisplayPosterBundle:Poster:event }

os2display_poster_occurrence:
    path:     /api/os2display_poster/occurrence
    defaults: { _controller: Os2DisplayPosterBundle:Poster:occurrence }

os2display_poster_search:
    path:     /api/os2display_poster/search
    defaults: { _controller: Os2DisplayPosterBundle:Poster:search }

os2display_poster_search_events:
    path:     /api/os2display_poster/search_events
    defaults: { _controller: Os2DisplayPosterBundle:Poster:searchEvents }
