os2display_poster_events:
    path:     /api/os2display_poster/events
    defaults: { _controller: Os2DisplayPosterBundle:Poster:events }

os2display_poster_event:
    path:     /api/os2display_poster/events/{id}
    defaults: { _controller: Os2DisplayPosterBundle:Poster:event }

os2display_poster_occurrence:
    path:     /api/os2display_poster/occurrence
    defaults: { _controller: Os2DisplayPosterBundle:Poster:occurrence }

os2display_poster_options:
    path:     /api/os2display_poster/option
    defaults: { _controller: Os2DisplayPosterBundle:Poster:options }
