services:
    os2display.poster.service:
        class: Os2Display\PosterBundle\Service\PosterService
#        arguments: ['@service_container']
#        tags:
#        - { name: kernel.event_listener, event: os2display.core.pre_push_channels, method: prePushChannels }
#        - { name: kernel.event_listener, event: os2display.core.pre_push_channel, method: prePushChannel }
#        - { name: kernel.event_listener, event: os2display.core.post_push_channels, method: postPushChannels }
